spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password1234
  jpa:
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          sample.url: http://127.0.0.1:3000
      okhttp:
        enabled: true